import '@/styles/globals.css'

import { Providers } from '@/app/providers'
import { locales } from '@/config/locale'
import Locale from 'intl-locale-textinfo-polyfill'
import type { Metadata } from 'next'
import { getMessages, unstable_setRequestLocale } from 'next-intl/server'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  // Enable static rendering
  unstable_setRequestLocale(locale)

  const { direction } = new Locale(locale).textInfo

  const messages = await getMessages()
  return (
    <html lang={locale} dir={direction} suppressHydrationWarning>
      <body className={inter.className}>
        <Providers messages={messages}>{children}</Providers>
      </body>
    </html>
  )
}
